s = ''
f = open('codon.txt')

cod = {}
temp = ''


for i in f:
    line = i.split()
    for j in xrange(len(line)):
        #print j
        if len(line[j]) == 3:
            temp = line[j]
        else:
            cod[temp] = line[j]

#print cod

f.close()

#print cod

res = 1

for i in 'MLPNIWGHPMNGFFDSQNLSRKQQAFRDGLIMMYFASFSSWGQQEPETCNDQLHNYPYMMLICYPLEAWNSMRHWVYHFWLGKHYFREWCAGHYDSFPGEYYTSWIWYTLLNPYEKFSPCEYMHVCYWNFTMLDMQPRAVWWWAHYSLSSDFARCEVGDPIDDSACVTHRNMCMQHFASGAVKRCCGMRYIISRILHAAARISWWWTTDWIEKRANRTEVAEALQFSYSDDTLQSTNGSYSASAWPWKCPQALWEDICWFVKRANHLAHTFFNRLLSVLGHPRSYQGPDDSFDKYKWGNNFYNVSIVSIKDPGHGRGHWHIRIGLFVMQSTYDAIMISQQPNMGMVGSCTLFNMMVHFMWYKMSMYFHLDDTEWTSTFRGAMYPDRITNECAWCLLATNTSKPWHPILPHHGIACGQEGYSFWEYWKIEQLENLCVNYYSDHFRWQRAWHSKKFRNWMGIWWKMQCVMADCMADNRTYIYWFRFESHDGWMQGEDVDVEYAQFDHHKFSDEHWIRRTQQWEETKFIHSENTCLWNDCWSYELYDMKIGGMTYDHLIGFDVWNLWQGGDRMSHPSGLKCNGTYTATAQTHFYMNNGWTVKMIMIMKRCQYYDPPWTKPVNFSCWKRFWSAHRTYLDIAFGNWNTQPIRGWEDSYDHVKQMIWLTYSEGLCHAIEYDAFTRWMKCTKSFSSQSLHWPWMTTRCWFFHHQMLTEFDHWGRYMDLNYPMIIENWPLVPKRYAPIVDMYESETKGEHTLYEYCNACMYMWWMILDNSCMVIRAYKEHECGEYHSEYILDHMHPRSVAIQSDKKMPTQVCVHYYFLLMIYCESRFVAVGIKCVNRLPHSKGEQMTETWRIQMSNYMWDVVPELNMGMVYIWLNLMVAKQYCHGDWVMEWSGIGIDMTRLEDACCMRPIFWWPSCMCTYSWMNRRMFPTVQRRIHVAASCTDYVWGKHMFNCMPLPNNIIHIFFWEGFKRFNQWYFFVKPCALGLSEWNFFPLDAWQ':
    temp = 0
    for j in cod:
        if cod[j] == i:
            temp += 1
    res *= temp
    
print res*3 % 1000000


    